#!/bin/bash

printHelp () {
	echo "Usage: dotinstall [-OPTION] [ARG]"
	echo "	-s setup - attempts to create a symbolic link .bash_aliases file to user's home directory"
	echo "	-d disconnect - removes symbolic link"
	echo "	-a append - adds a new alias to .bash_aliases file"
	echo "	-r remove - removes an alias from .bash_aliases file"
}

createSymbolicLink () {
	echo "blahblah"	
}

appendAlias () {
	echo "$1" >> .bash_aliases
}

removeAlias () {
        grep -q "$1" .bash_aliases
        if [[ $? -eq 0 ]]; then
                sed -i "/$1/d" .bash_aliases
        else
                echo "ERROR: No matching alias found."
        fi

}

while getopts ":hsda:r:" opt; do
  case $opt in
    h) 
	    printHelp 
	    ;;
    s) 
	    echo "s" 
	    ;;
    d) 
	    echo "d" 
	    ;;
    a) 
	    appendAlias "$OPTARG"
	    ;;
    r) 
	    removeAlias "$OPTARG" 
	    ;;
    \?) 
	    echo "Option not supported"
	   printHelp 
	    ;;
  esac
done
